// AstroFrontEnd/src/App.tsx
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import Planets from './pages/Planets';
import Moons from './pages/Moons';
import React from 'react';

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Planets />} />
        <Route path="/moons" element={<Moons />} />
      </Routes>
    </BrowserRouter>
  );
}

export default App;

// AstroFrontEnd/src/App.svelte
<script>
	import { Router, Link, Route } from 'svelte-routing';
	import Planets from './Planets.svelte';
	import Moons from './Moons.svelte';
</script>

<Router>
	<nav>
		<Link to="/">Home</Link>
		<Link to="planets">Planets</Link>
		<Link to="moons">Moons</Link>
	</nav>
	<div>
		<Route path="/"></Route>
		<Route path="planets" component={Planets} />
		<Route path="moons" component={Moons} />
	</div>
</Router>
